### ISSUE TITLE
Target build not vuln  (Win10Pro)

### ISSUE THREAD

**Issue by Micape** [zerosum0x0/koadic#103]
target Win10 Pro 1809
mshta is ok
bypass with error why
(koadic: imp/ele/bypassuac_eventvwr)# run
[-] Zombie 0: Job 0 (implant/elevate/bypassuac_eventvwr) failed!
[-] Target build not vuln (100000000): The target may not be vulnerable to this implant. Set IGNOREBUILD to true to run anyway.

**Comment by TheNaterz** [comment]
Your target may not be vulnerable to this implant. You could set IGNOREBUILD to true to run anyway.

Alternatively, use another bypass implant.

**Comment by zerosum0x0** [comment]
1809 is 17763, try `bypassuac_compdefaults` or `bypassuac_fodhelper`.

If they ain't work just the way it is.
