### ISSUE TITLE
koadic and antivirus

### ISSUE THREAD

**Issue by Anton19780301** [zerosum0x0/koadic#105]
Good day.
I apologize for the dumb question.
Give advice - the link is detected by the herester analysis of Kaspersky Anti-Virus as a virus. I attach the screen.
Just interesting, is there any way to deceive antivirus?
I launched this project in my office and was pleasantly surprised by its capabilities. But antivirus has to be disabled manually.
![viber image 2019-06-07 , 14 30 36](https://user-images.githubusercontent.com/51848186/59548696-c7e54c80-8f5b-11e9-9a69-fd7ce62f2135.jpg)

**Comment by TheNaterz** [comment]
¯\\\_(ツ)_/¯
