### ISSUE TITLE
Domain fronting support

### ISSUE THREAD

**Issue by pbssubhash** [zerosum0x0/koadic#106]
Hey,

Domain fronting can be a nice way to circumvent enterprise firewalls while initial compromise phase. To achieve that the agent has to add a custom header for all communications. I guess it's a small change. Do you have any plans to implement that or if you can guide me on if there is a single place where the request parameters are defined, it'd be just adding a header there.

**Comment by TheNaterz** [comment]
We don't have plans to support this, but you're more than welcome to try it out on your own.

Here's where you can add headers in the stdlib:
https://github.com/zerosum0x0/koadic/blob/e136fe8c6c021c885e8720b22aa6b0c50d371d4c/data/stager/js/stdlib.js#L527-L545
