### ISSUE TITLE
hta open window

### ISSUE THREAD

**Issue by LIZySARA** [zerosum0x0/koadic#111]
![s](https://user-images.githubusercontent.com/22563762/60755938-38313c00-9ff7-11e9-86ff-5859f157b423.png)

Hello,
This error is due to the fact that the koadic is not executed
Is there no way to solve this problem?

**Comment by TheNaterz** [comment]
You're getting this because there's no route from your target to your Koadic server. Can't really help with that tho, that's something you need to figure out on your own.
