### ISSUE TITLE
Supported OSes?

### ISSUE THREAD

**Issue by pandalatte** [zerosum0x0/koadic#114]
Hi everyone!

I've decided to try Koadic, seems like a great tool!
I have a whole bunch of testlab VMs in Virtualbox - from XP to 10.
But in my situation, the mshta command throws an error on any pre-8.1 Windows.

RunDLL
"There was a problem starting (koadic url) //././.\\/.\./.\./\\.\\.\/\/\./\.\\./.\\mshtml"
"The specified module could not be found"

Here is the list of Win versions I've tried:

Win XP - error
Win 2003 Server - error
Win 7 - error
Win 2008 - error - big blank window, nothing more
Win 8.1 - ok
Win 10 LTSB - ok

Does this mean that old (pre 8.1) versions are out of luck? Thanks!

**Comment by TheNaterz** [comment]
Oh yep yep yep, we actually saw this a couple weeks ago and I forgot until now. Older Windows can't process the long length of our hacky RunDLL bypass. We just need to make that length smaller. One second!

**Comment by TheNaterz** [comment]
I just went ahead and pushed. Relevant lines are here https://github.com/zerosum0x0/koadic/blob/master/koadic#L35

and here
https://github.com/zerosum0x0/koadic/blob/master/koadic#L80

We haven't fully tested this whole shindig on other versions, but let us know if smaller lengths for those paths fixes the issue.

**Comment by TheNaterz** [comment]
If 5 doesn't work, try less?

**Comment by TheNaterz** [comment]
I'm currently doing some testing on a Server 2003, and length doesn't seem to be an issue. I am getting occasional errors, so I think it's something with the dot-slashes. Some combinations might be bad. Still testing.

**Comment by TheNaterz** [comment]
I think I've narrowed it down. Forward slashes aren't playing nicely on Server 2003. I'll take those out for now. Your lab environment is more broad than mine, so let me know if this fixes the problem :D

**Comment by pandalatte** [comment]
Yup! Works on everything now - XP, 7 and so on :) Thanks!

(Side issue: its getting caught by AV over the plain http, obviously. I'll do some tests over https tonight... and do you have any plans to add some obfuscation in future versions?) Thanks for your great work!

**Comment by TheNaterz** [comment]
We support XOR ciphering for obfuscation, but that's about it. AFAIK, the most obfuscation we can achieve is passing a big blob to an eval which can trigger a different red flag. Open to other methods if we can implement!
