### ISSUE TITLE
timeout question

### ISSUE THREAD

**Issue by sqift** [zerosum0x0/koadic#115]
Hello
this program is awesome
I can’t figure it out - is it possible to keep the connection between the zombies and the server constantly without any additional actions? Otherwise, the client is lost after half an hour. Now I use the command execution method every 3 minutes

**Comment by TheNaterz** [comment]
Sounds like anti-virus or something else is killing your zombies. It's designed to stay active, zombies will fork periodically to keep themselves alive and will continue polling against the server. You would have to do more investigation as to why the connection keeps dropping.

**Comment by sqift** [comment]
I realized that the provider was dropping packets
thx
