### ISSUE TITLE
Automatic command 

### ISSUE THREAD

**Issue by futex** [zerosum0x0/koadic#116]
Hi, I haven't find, so sorry if i'm wrong, is it possible to automatically run commands at zombie connection?
Thank

**Comment by TheNaterz** [comment]
Use `set MODULE` on your stager before running.

**Comment by futex** [comment]
I launch koadic with an autorun.rc, do you have example of how i can add module inside or in a separate file launch bu the aurotun.rc?

**Comment by TheNaterz** [comment]
Just make sure that `set MODULE` is defined in your autorun for any relevant stagers before you launch them.

**Comment by futex** [comment]
yes ok, but how put the MODULE option? for example in autorun.txt run as koadic --autorun autorun.txt

set MODULE implant/manage/exec_cmd 
set CMD whoami

failed

**Comment by TheNaterz** [comment]
After setting the module in your autorun, then `use implant/manage/exec_cmd` to set the options. Then go back to the stager to run it.

**Comment by TheNaterz** [comment]
This isn't ideal and our implementation of this is shaky. When I get some time, I'll work on this more.

**Comment by futex** [comment]
ok, yes can be a useful option
Thank
