### ISSUE TITLE
Server setup fails when using SSL Certificates

### ISSUE THREAD

**Issue by vrtlabs** [zerosum0x0/koadic#118]
There is an issue when starting a stager with SSL Certificates.

In stager.py keypath and certpath are passed as a list. These parameters need to be strings. See below code for issue and fix.

core/stager.py
issue:
`server = core.server.Server(port, core.handler.Handler, keypath, certpath, self.shell, self.options)`
fix:
`server = core.server.Server(port, core.handler.Handler, keypath[0], certpath[0], self.shell, self.options)`

In server.py certpath is passed but not defined. This parameter should be `self.certpath` referencing the variable from __init__.

core/server.py
issue:
`self.http.socket = ssl.wrap_socket(self.http.socket, keyfile=self.keypath, certfile=certpath, server_side = True)`
fix:
`self.http.socket = ssl.wrap_socket(self.http.socket, keyfile=self.keypath, certfile=self.certpath, server_side = True)`

**Comment by TheNaterz** [comment]
Gotcha, thanks for the heads up. I somehow confused split() and strip() when I was changing things lol. Pushing in a sec!

**Comment by vrtlabs** [comment]
Lightning fast update... Thanks and great tool.
