### ISSUE TITLE
mimikatz_dynwrapx

### ISSUE THREAD

**Issue by k0l0ss** [zerosum0x0/koadic#122]
Hello, is there a fix for this?

![ID_1675286587_1578495222369](https://user-images.githubusercontent.com/29979342/71994945-f305f500-3239-11ea-905d-fd4c5a44c624.png)
mimikatz_dotnet2js works

**Comment by TheNaterz** [comment]
Pushed a fix, had to copy the make_arrDLL function up to the job class.

**Comment by k0l0ss** [comment]
Hello, the py crash is gone but we continued with the following issue:
![ID_850329077_1578581155924](https://user-images.githubusercontent.com/29979342/72082032-d633f500-32ff-11ea-8521-fff1dbe60cda.png)
hope it helps,

thx

**Comment by TheNaterz** [comment]
I forgot to copy over the return for that function. I just tested it and it looks good, but let me know.

**Comment by k0l0ss** [comment]
Works,

Thx for the support. 

Keep the good work
