### ISSUE TITLE
tcp Scan(implants) Issue

### ISSUE THREAD

**Issue by jeffinm** [zerosum0x0/koadic#131]
Hi,
1. When i am using tcp scan implant i am facing issues. When scanning remote machine it is showing the machine is not up, but machine is UP and running fine. 

(koadic: imp/sca/tcp)# set RHOSTS 10.0.2.6
[+] RHOSTS => 10.0.2.6
(koadic: imp/sca/tcp)# set TIMEOUT 6
[+] TIMEOUT => 6
(koadic: imp/sca/tcp)# set ZOMBIE 1
[+] ZOMBIE => 1
(koadic: imp/sca/tcp)# run
[-] Zombie 1: Job 1 (impl[*] Zombie 1: Job 1 (implant/scan/tcp) created.
**ant/scan/tcp) 10.0.2.6            1         not up     00000000**  
[+] Zombie 1: Job 1 (implant/scan/tcp) completed.
(koadic: imp/sca/tcp)# 
(koadic: imp/sca/tcp)# info
 
        NAME        VALUE               REQ     DESCRIPTION     
        -----       ------------        ----    -------------   
        RHOSTS      10.0.2.6            yes     name/IP of the remotes
        RPORTS      22,80,135,139,44... yes     ports to scan   
        TIMEOUT     6                   yes     longer is more accurate
        CHECKLIVE   true                yes     check if host is up before checking ports
        ZOMBIE      1                   yes     the zombie to target
-------------

2. And when i make the same machine as zombie and set rhosts and zombie IP it is showing open ports as well. 

(koadic: imp/sca/tcp)# set RHOSTS 10.0.2.6   (same ZOMBIE machine)
+] RHOSTS => 10.0.2.8
(koadic: imp/sca/tcp)# run
[*] Zombie 1: Job 2 (implant/scan/tcp) created.
[*] Zombie 1: Job 2 (implant/scan/tcp) 10.0.2.6            22        closed     80072efd  
[*] Zombie 1: Job 2 (implant/scan/tcp) 10.0.2.6            80        closed     80072efd  
[+] Zombie 1: Job 2 (implant/scan/tcp) 10.0.2.6            135       open       00000000  
[+] Zombie 1: Job 2 (implant/scan/tcp) 10.0.2.6            139       open       80072f78  
[*] Zombie 1: Job 2 (implant/scan/tcp) 10.0.2.6            443       closed     80072efd  
[+] Zombie 1: Job 2 (implant/scan/tcp) 10.0.2.6            445       open       80072efe  
[+] Zombie 1: Job 2 (implant/scan/tcp) 10.0.2.6            3389      open       00000000  
[+] Zombie 1: Job 2 (implant/scan/tcp) completed.
(koadic: imp/sca/tcp)# 

3. Also if i set CHECKLIVE status false, it is showing ports are open for machines which are not even in the network as well.

4. If i scan above machine using nmap i can see that machine is UP and running,
root@kali:~# nmap 10.0.2.6
Starting Nmap 7.80 ( https://nmap.org ) at 2020-02-13 05:52 EST
Nmap scan report for 10.0.2.6
**Host is up (0.00033s latency).**
Not shown: 999 filtered ports
PORT     STATE SERVICE
**3389/tcp open  ms-wbt-server**

**Can you please See why it is showing like this**

**Comment by TheNaterz** [comment]
Port scanning in Koadic uses JScript to attempt to talk HTTP to various ports. From what we've seen, there are certain behaviors that are observed if the targeted port is open or closed, but it's not really anything more than an educated guess. If we had access to raw sockets, then it would be a different story. For now, treat this implant as more of an interesting idea rather than a true reconnaissance method.
