### ISSUE TITLE
possible newb issue?

### ISSUE THREAD

**Issue by chppppp** [zerosum0x0/koadic#135]
Hi - I am new to Koadic, it was recommended by an infosec friend. 

I am experimenting with the `cmdshell` and while it appears to not echo back the results of your command (thats ok), i cannot seem to achieve any level of execution with it. running a command like `echo test > test.txt` does not create the test.txt file. I am wondering if I am using this incorrectly? 

Thank you so much for your work on Koadic, this is a super cool project. Your help is appreciated.

**Comment by chppppp** [comment]
Also - if you guys hang out in a slack or discord and dont mind a newb pulling your ear i would love an invite :P 

Thanks again.

**Comment by TheNaterz** [comment]
Well it SHOULD be echoing back command results. Weird, that it's not running. We don't have a slack or discord, but you can send me a DM on Twitter. https://twitter.com/the_naterz

**Comment by zerosum0x0** [comment]
We are already piping commands into text files in order to retrieve the output.

`cmdshell` is a shortcut to `implant/manage/exec_cmd`

The module has a `DIRECTORY` value (default `%TEMP%`) where it writes UUID-named text files. It is possible you may need to change the default output directory.

**Comment by TheNaterz** [comment]
From what I remember, this was something to do with the target environment. I don't think it's a Koadic issue, but we'll keep an eye out if we see this in the wild at all.
