### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by Koploseus** [zerosum0x0/koadic#137]
Hello,

I have a time out connection for every stager 

![image](https://user-images.githubusercontent.com/25018500/81726329-802ab600-9487-11ea-9150-6c8ad29e1674.png)

I am testing it on a virtual machine Windows Server 2016 without any AV

**Comment by zerosum0x0** [comment]
We've seen this behavior in the past with Windows Defender blocking after initial staging. It's a cat and mouse game to write new evasions.

Gonna close issue since this is several months old.
