### ISSUE TITLE
playsound module

### ISSUE THREAD

**Issue by green-butterfly** [zerosum0x0/koadic#138]
Hey guys.
I have an issue with the sound module.
When i try to turn off / on the sound on the zombie machine with "Sounds" command, i get the output:

**[ - ] You do not have playsound module installed. Please run 'pip install playsound' to enable this feature!**

After playsound installation, i get the same output.
Please advise.
Maybe i'm missing something.

P/S: thank you for this great tool, i realy love it ! keep on rockin ! :)

**Comment by serpant17** [comment]
Hey green-butterfly,

You might be using the wrong or outdated pip. Try this:

$ pip3 install playsound
from playsound import playsound

**Comment by green-butterfly** [comment]
Hey serpant17,

That was the problem, I used the wrong pip.

**pt@machine:~$** pip3 show playsound
WARNING: Package(s) not found: playsound.

After playsound installation with pip3:

**pt@machine:~$** pip3 show playsound
Name: playsound
Version: 1.2.2
Summary: Pure Python, cross platform, single function module with no dependencies for playing sounds.
Home-page: https://github.com/TaylorSMarks/playsound
Author: Taylor Marks
Author-email: taylor@marksfam.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: 
**pt@machine:~$**

The playsound module in now enabled, and Koadic recognize the "Sounds" command. 

Thanks. :100: :+1:
