### ISSUE TITLE
ModuleNotFoundError: No module named 'win32com'

### ISSUE THREAD

**Issue by darkshadowman80** [zerosum0x0/koadic#145]
Os: Kali linux
after installing requirements
and ./koadic
![Screenshot 2021-01-24 15:37:21](https://user-images.githubusercontent.com/77925360/105632078-21ad3880-5e5a-11eb-9912-db8d74e6e8e3.png)

**Comment by zerosum0x0** [comment]
`win32com` appears to be part of the `pywin32` library, which according to [this issue](https://github.com/mhammond/pywin32/issues/1372) is a Windows only library. It is odd to see something in the `/usr/local/lib/python3.9/dist-packages/` folder attempting to load something that doesn't exist for Linux.

At any rate, from the screenshot it looks like an older version of Kali. I just installed `Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux` and everything ran fine.

```sudo apt install python3-pip
python3 -m pip install -r requirements```

**Comment by zerosum0x0** [comment]
Another note, I don't think we actually do anything directly with WMI from Python. Several of the JScript payloads use WMI, and we use some impacket imports that might use it internally.

It seems like something is busted in one of the Python package managers to give you Windows libraries on Linux. Gonna close this issue for now but if it's on our side we can re-open.
