### ISSUE TITLE
Koadic wont install

### ISSUE THREAD

**Issue by uprizzz** [zerosum0x0/koadic#150]
very new to frameworks. i paste the install command and i get this response

![image](https://user-images.githubusercontent.com/85844355/121817929-cac2c700-cc73-11eb-8f3f-4de9d4d61559.png)

im doing this in the Root Terminal of TailsOS because its the place where the book im reading tells me to do this

any help is much appriciated!

**Comment by zerosum0x0** [comment]
Looks like DNS error. That is an environment issue that is out of scope for this project to debug.
