### ISSUE TITLE
Cryptologically-Secure Comms

### ISSUE THREAD

**Issue by leoloobeek** [zerosum0x0/koadic#23]
I have a personal project that works off of VBScript and DotNetToJScript (similar to koadic) and I spent some time getting Encrypted Key Exchange for underlying crypto for all comms. The implementation was almost exact to how [Empire does it](https://github.com/EmpireProject/Empire/wiki/Staging).

Is there any interest if having that thrown into koadic? Since I already did some of the legwork here I figured I would just offer to share and see if we can get it nicely into koadic. Naturally it would add some additional communications and code executed on the zombie side.

Just an offer.. let me know! Either way great work on the project and look forward to giving it a go!

**Comment by TheNaterz** [comment]
Yeah it sounds interesting. If you could work on making a PR, that would be helpful :)

**Comment by leoloobeek** [comment]
Alright I'll see what I can piece together.
