### ISSUE TITLE
MSHTA does not serve payload in memory

### ISSUE THREAD

**Issue by passwordleak** [zerosum0x0/koadic#35]
MSHTA downloads and executes the html in %userprofile%\appdata\local\Microsoft\Windows\INetCache\IE

This is similar to downloading and executing using bitsadmin or whatever. And is susceptible to antivirus detection.

**Comment by zerosum0x0** [comment]
We know it ends up in the local cache.

So far the only AV that I know of that _was_ reliably detecting it was Windows Defender (Trojan:JS/Koadic.G!Attk). We bypassed it but now there might be a secondary detection (see #7).

What's funny though, is that even when Windows Defender detects it, the script still runs, and the zombie is fully functional. So there is some level of in-memory going on. I don't know if MS was lazy or if this is a limitation of AMSI.
