### ISSUE TITLE
An exception of type error occured. Arguments: (98, 'Address already in use')

### ISSUE THREAD

**Issue by DoorK33per** [zerosum0x0/koadic#39]
I am using ngrok i dont know why does it say this. Also, I am using LHOST not SRVHOST. If you know how to use it with url as HOST please share.

**Comment by DoorK33per** [comment]
My issue is if i am using ngrok my port is already in use. is there a way to do both, as my ip is dynamic. Second where the does actual url point to the folder in my system??

**Comment by TheNaterz** [comment]
If ngrok is binding to a port that you want to use, you'll need to figure out how to locally forward traffic to a different port and launch your handler there instead. If you want to use a url, then you need to specify the url as your LHOST and set KEYPATH and CERTPATH appropriately. The handler doesn't point to any folder on your system. Koadic listens on the handler for the stager request and then handles sending over the payload to launch a zombie.
