### ISSUE TITLE
multiples errors to use the framwork

### ISSUE THREAD

**Issue by gearcapitan** [zerosum0x0/koadic#41]
![windows 8 1 x64-2018-02-06-14-33-16](https://user-images.githubusercontent.com/13740942/35882846-18aba092-0b4b-11e8-9270-d38fe4528185.png)

![kali linux-2018-02-06-14-34-27](https://user-images.githubusercontent.com/13740942/35882803-f9b0a688-0b4a-11e8-9f06-ee2878167ee7.png)

any advice?....

**Comment by TheNaterz** [comment]
My best guess is that your zombie doesn't have write permissions to the target directory defined in exec_cmd. Either run the stager from an elevated command prompt or change the target directory. Default directory is %TEMP% which should be world writeable, weird if it isn't.
