### ISSUE TITLE
mimikatz_dotnet2js needs to be changed to not need Fork32Bit=true

### ISSUE THREAD

**Issue by zerosum0x0** [zerosum0x0/koadic#46]
The SquiblyTwo stager from @caseysmithrc uses wmic.exe, which unlike other stagers is not in the syswow64 or system32 folders (instead is in wbem of each).

This screws up mimshim because our code to fork 32 bit from 64 bit is busted and assumes syswow64 folder. 

But this additional fork is also an unnecessary step that is only required because we only use the 32-bit dynwrapx. For dotnet2js, we can just stay in 64-bit mode for all operations.

We already have mimishim.x64.dll in the ./data/bin folder. We just need to fix this. Until then SquiblyTwo is broken for using dotnet2js unless the system is x86.

**Comment by TheNaterz** [comment]
Stdlib retrieves target architecture as part of its initial staging information grab (Koadic.user.Arch) and is exposed to Koadic via session.arch. Zerosum and I discussed this a bit, should be an easy enough fix whenever we can get around to it.

**Comment by zerosum0x0** [comment]
fixed in  96d57fde3a5060adc1351e713e8ef52186690166
