### ISSUE TITLE
rundll32 stager is busted

### ISSUE THREAD

**Issue by zerosum0x0** [zerosum0x0/koadic#47]
This stager worked at some point and has regressed somehow. What is odd is that the mshta stager, the main stager, uses rundll32 internally.

**Comment by TheNaterz** [comment]
@Aleph-Naught- has made a lot of headway today on this, even may have found a defender bypass when executing rundll32 javascript? Right now, experiencing an issue in the DoWork loop. New jobs are not run and cause the Zombie to time out. Idling also appears to time a Zombie out. Initial fork appears to be working now, additional forks are having issues? JScript is almost impossible to debug :(

**Comment by TheNaterz** [comment]
Tired, disregard the close

**Comment by zerosum0x0** [comment]
Fixed in 82c2de4
