### ISSUE TITLE
Undefined name 'ThunderstruckJob' in cranberry.py

### ISSUE THREAD

**Issue by cclauss** [zerosum0x0/koadic#50]
https://github.com/zerosum0x0/koadic/blob/master/modules/implant/fun/cranberry.py#L28

flake8 testing of https://github.com/zerosum0x0/koadic on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./modules/implant/fun/cranberry.py:28:33: F821 undefined name 'ThunderstruckJob'
        self.dispatch(payloads, ThunderstruckJob)
                                ^
1     F821 undefined name 'ThunderstruckJob'
1
```

**Comment by TheNaterz** [comment]
Good lookin out. I don't even know if this implant works tbh haha. Might as well be fixed!
