### ISSUE TITLE
Persistence calling a dead session

### ISSUE THREAD

**Issue by basedzues** [zerosum0x0/koadic#58]
What happens is that when i persist with the registry module using mshta module , it does add the value/key in the registry and does run at startup, but what happens is that when i close the terminal with the session(attacker) and run koadic again (there is  a new session) , when i restart the machine of the victim the registry(on the victim machine ) tries to call the the session(on the attacker) at startup , but it can not connect because the session was closed on the attacker machine and there is now a new session...

Is there something i am doing wrong?

**Comment by TheNaterz** [comment]
My best guess is that your endpoint changed when you restarted Koadic. The registry value is set to the listener payload of Koadic on the first iteration and if it's not the same the second time around, it's not going to establish a new session.

Try setting the same endpoint value (e.g. test123) and port (e.g. 9999) for both iterations of Koadic.

**Comment by basedzues** [comment]
okay 
But It could help alot if you can make the sessions  optional (depend on the attacker if they want to change it or not) after the koadic terminal is closed, so that we could not loose that persistency when we open it again

**Comment by TheNaterz** [comment]
That's not how is Koadic is designed and we don't intend to support that kind of behavior. All I can is, use the same ENDPOINT and PORT for your stagers on subsequent runs of Koadic. The easiest way to do this would be to take advantage of the autorun feature. You can describe all of your listeners in the autorun file and Koadic will set those up on execution when running with --autorun.
