### ISSUE TITLE
Change current command & control  on DNS over HTTPS (DoH)

### ISSUE THREAD

**Issue by r00t-Taurus** [zerosum0x0/koadic#66]
How do you like the idea of change current command & control on DNS over HTTPS (DoH)?

PS `https://outflank.nl/blog/2018/10/25/building-resilient-c2-infrastructues-using-dns-over-https/`

**Comment by TheNaterz** [comment]
So I read through the article and nothing is really jumping out at me. Can you explain a little about what you think the benefits of using this method would be?

**Comment by TheNaterz** [comment]
OK well a couple things about that:
- The initial stager that talks to Koadic is going to stand out anyways, if used over HTTP. Anyone who is diligently observing network traffic will see the first request and it will raise red flags.
- If we can talk to Koadic and we have the ability to talk over an encrypted channel, you might as well just talk to Koadic over HTTPS.

Eventually you have to talk to something that's not Google. If stage 2 talks back to the C2 over an unencrypted channel, the whole point is moot. If you can talk to Koadic over an encrypted channel, then DNS over HTTPS is just unnecessary.

**Comment by TheNaterz** [comment]
So yeah, basically I don't see any real benefit for this, but we'll continue keeping an eye on better methods for communications.
