### ISSUE TITLE
enum_domain_info - can't access registry

### ISSUE THREAD

**Issue by Dexessus** [zerosum0x0/koadic#70]
**Test environment**
Attacker: Kali Linux
Victim: Windows 10 (Build: 1803) 17134.345

Got elevated access via mshta.
```                      
        Status:                 Alive                                  
        Listener:               0                               
        IP:                     176.119.75.100                  
        Hostname:               DESKTOP-VICTIM                                   
        OS:                     Windows 10 Pro                  
        OSBuild:                17134                           
        OSArch:                 64                              
        Elevated:               YES!   
```

Then run `implant/gather/enum_domain_info`
```
[v] Server: <Server(Thread-145, started daemon 140003525306112)> Sesson <core.session.Session object at 0x7f551ab48e10>
[*] Zombie 1: Job 8 (implant/gather/enum_domain_info) created.
[v] session::get_created_job - fetched job.key = eaa59c0d70d14dcf9aa4bef132d76678
[v] handler::reply() - sending status 201 with 32 bytes to ('176.119.75.100', 49886)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 49889)
[v] handler::find_session() - found session.key = 0111a2fdbe214e9dbae17baf8e0ae338
[v] self.params:  {'sid': ['0111a2fdbe214e9dbae17baf8e0ae338'], 'csrf': ['stage']}
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 49890)
[v] handler::find_session() - found session.key = 0111a2fdbe214e9dbae17baf8e0ae338
[v] self.params:  {'sid': ['0111a2fdbe214e9dbae17baf8e0ae338'], 'csrf': ['eaa59c0d70d14dcf9aa4bef132d76678']}
[v] session::get_job() - fetched job_key = eaa59c0d70d14dcf9aa4bef132d76678
[v] handler::reply() - sending status 200 with 10016 bytes to ('176.119.75.100', 49890)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 49891)
[v] handler::find_session() - found session.key = 0111a2fdbe214e9dbae17baf8e0ae338
[v] self.params:  {'sid': ['0111a2fdbe214e9dbae17baf8e0ae338'], 'csrf': ['eaa59c0d70d14dcf9aa4bef132d76678']}
[v] session::get_job() - fetched job_key = eaa59c0d70d14dcf9aa4bef132d76678
[-] Zombie 1: Job 8 (implant/gather/enum_domain_info) failed!

[-] Error (80070002): Íå óäàåòñÿ îòêðûòü äëÿ ÷òåíèÿ ðàçäåë ðååñòðà "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\History\MachineDomain". 

[v] handler::reply() - sending status 200 with 0 bytes to ('176.119.75.100', 49891)
[v] handler::reply() - sending status 201 with 0 bytes to ('176.119.75.100', 49869)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 49892)
[v] handler::find_session() - found session.key = c564680ebec848f5b4304afa11d7fc3b
[v] self.params:  {'sid': ['c564680ebec848f5b4304afa11d7fc3b'], 'csrf': ['stage']}
```
This error with wrong encoding (cyrillic OS), but after decode it means: `"Cant' access registry section for reading".`

And I think, this is because - this path does not exist. 
I checked at machines at work, at home, at friends - they all have some computers in their network, but they don't have this registry section.
![screenshot - 08_11](https://user-images.githubusercontent.com/7254696/48188972-b134a280-e347-11e8-8cfa-25f59e99c402.jpg)

As you can see, "History" folder is empty.

I checked if this victim machine can see other computers via `net view /all`
Yes, it can:
```
C:\Users\admin>net view /all
Имя сервера            Заметки

-------------------------------------------------------------------------------
\\DESKTOP-VICTIM
\\DESKTOP-TARGET
```

I don't know, how to fix it, and maybe it will be better to use another method to do same as `enum_domain_info`
Or before doing job, test if this registry folders exist, if no - report it with simple error message.

**Comment by TheNaterz** [comment]
Thanks for the detailed issue!

That's weird. In all my testing, this registry value is consistent for domain joined machines. I can add some more conditions to check for the existence of the domain's FQDN. Windows shell environment variables may contain this information, for example. I think we can also use `whoami /FQDN`. I'll do some testing tomorrow and a get an update pushed.

**Comment by TheNaterz** [comment]
Can you pull and see if enum_domain_info works now?

**Comment by Dexessus** [comment]
Oh, got the same error as in hashdump_dc (not hashdump_sam as I created thread)


```
[v] Server: <Server(Thread-15, started daemon 139793667114752)> Sesson <core.session.Session object at 0x7f243e2e7550>
[*] Zombie 1: Job 2 (implant/gather/enum_domain_info) created.
[v] session::get_created_job - fetched job.key = 4e9e06a055f240628e595af7a67cef53
[v] handler::reply() - sending status 201 with 32 bytes to ('176.119.75.100', 49772)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 49776)
[v] handler::find_session() - found session.key = 2c47beeb53c2494ead88889d7bc9bf54
[v] self.params:  {'sid': ['2c47beeb53c2494ead88889d7bc9bf54'], 'csrf': ['stage']}
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 49777)
[v] handler::find_session() - found session.key = 2c47beeb53c2494ead88889d7bc9bf54
[v] self.params:  {'sid': ['2c47beeb53c2494ead88889d7bc9bf54'], 'csrf': ['4e9e06a055f240628e595af7a67cef53']}
[v] session::get_job() - fetched job_key = 4e9e06a055f240628e595af7a67cef53
[v] handler::reply() - sending status 200 with 10671 bytes to ('176.119.75.100', 49777)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 49778)
[v] handler::find_session() - found session.key = 2c47beeb53c2494ead88889d7bc9bf54
[v] self.params:  {'sid': ['2c47beeb53c2494ead88889d7bc9bf54'], 'csrf': ['4e9e06a055f240628e595af7a67cef53']}
[v] session::get_job() - fetched job_key = 4e9e06a055f240628e595af7a67cef53

[+] Zombie 1: Job 2 (implant/gather/enum_domain_info) Detected Domain: %userdnsdomain% (DESKTOP-VICTIM)

[v] handler::reply() - sending status 200 with 0 bytes to ('176.119.75.100', 49778)
[v] handler::handle() - Incoming HTTP from ('176.119.75.100', 49779)
[v] handler::find_session() - found session.key = 2c47beeb53c2494ead88889d7bc9bf54
[v] self.params:  {'sid': ['2c47beeb53c2494ead88889d7bc9bf54'], 'csrf': ['4e9e06a055f240628e595af7a67cef53']}
[v] session::get_job() - fetched job_key = 4e9e06a055f240628e595af7a67cef53
[-] Zombie 1: Job 2 (implant/gather/enum_domain_info) failed!

[-] TypeError (800a138f): Íå óäàëîñü ïîëó÷èòü ñâîéñòâî "split" ññûëêè, çíà÷åíèå êîòîðîé íå îïðåäåëåíî èëè ÿâëÿåòñÿ NULL 

[v] handler::reply() - sending status 200 with 0 bytes to ('176.119.75.100', 49779)
```

Once again, cyrillic encoding.
If decode this message and translate to English, it means something like:
`Cannot read property 'split' of undefined or NULL`

**Comment by TheNaterz** [comment]
Nah nah this isn't an encoding thing, I'm just bad at javascript. I have a Russian version of Windows that I'm testing on and I can replicate your behavior now. Gonna do more testing and have proper fix out soon.

In regards to the current error, I'm pretty sure it's because your target isn't actually joined to a domain. Try running `whoami /fqdn`, and if you get an error, that's pretty much definitive.

**Comment by Dexessus** [comment]
> this isn't an encoding thing

I meant, that message goes in wrong encoding. For russian speaking users it's a little bit annoying. :)

> Try running `whoami /fqdn`, and if you get an error, that's pretty much definitive.

Yeah, got error.

So, it means, that even if I can see other computers via `net view /all` - it can't be used as pivot to access another machine in network? :(

**Comment by TheNaterz** [comment]
OK go ahead and pull now, I've got this working on my Russian version of Windows. You'll need to set CYRILLIC to true before running.

**Comment by TheNaterz** [comment]
> So, it means, that even if I can see other computers via net view /all - it can't be used as pivot to access another machine in network? :(

I mean, it still can. You can gather credentials from the target and if they are reused on other machines, then the target is still considered a pivot.

**Comment by TheNaterz** [comment]
In this instance, target does not appear to be joined to a domain. More conditions have been added to check for this. Will work on trying to get error messaged encoded correctly for cyrillic.

**Comment by Dexessus** [comment]
I see fix in `hashdump_sam`, tried - got no errors.
Also seen a cyrillic options.

But, this thread about `enum_domain_info` :)

And there is still the same error
`[-] TypeError (800a138f): Íå óäàëîñü ïîëó÷èòü ñâîéñòâî "split" ññûëêè, çíà÷åíèå êîòîðîé íå îïðåäåëåíî èëè ÿâëÿåòñÿ NULL `

Will be that fixed and do you plan to add cyrillic options to this module?

**Comment by TheNaterz** [comment]
OK I just read over your issue again, I somehow completely missed where this error was actually happening.

I assumed the split error that you were getting was because of new splits that I introduced with the recent FQDN changes, but that actually doesn't seem to be the case here. In your issue, your detected domain FQDN is "%userdnsdomain%". I have some logic that is supposed to catch on this value and skip over it. In your case, that isn't happening for some reason. So now Koadic thinks your domain FQDN in literally "%userdnsdomain%". Then it tries to parse the domain users which, lo and behold, is where the split error is actually happening because your target isn't joined to a domain and if Koadic hits this point, it assumes that it is.

So a few things:

1. I don't know why your enum_domain_info isn't catching on %userdnsdomain%. I'd ask that you go into data/implant/gather/enum_domain_info.js and add some alerts in "function findFQDN()" or something to figure out what's going on.

2. I can't replicate your error message being encoded incorrectly. The error is being generated by the JScript interpreter and we're simply passing the message back to Koadic and displaying it. On my Russian Windows, this error message is in English? So I have no idea what's going on with this one.

**Comment by TheNaterz** [comment]
Also, you don't need to set CYRILLIC anymore, we figured out a way to do it dynamically.
