### ISSUE TITLE
bug? in docker listeners and payload url can not same

### ISSUE THREAD

**Issue by hktalent** [zerosum0x0/koadic#72]
in my docker
must 
set SRVHOST my lan pc ip(192.168.1.30),not docker ip(172.17.0.2)
so 
please set the ip to paload
and listeners not use SRVHOST, use 0.0.0.0
in target can not acces the docker ip(172.17.0.2)
<img width="736" alt="image" src="https://user-images.githubusercontent.com/18223385/48656331-03b84200-ea5f-11e8-8324-51906a7bf25d.png">

**Comment by TheNaterz** [comment]
You need to set your SRVHOST to the IP that the target can connect to. If you want targets to connect through 192.168.1.30, you need to set that.

I don't really understand the issue. You will need to post more context.
