### ISSUE TITLE
how use sta/js/mshta in metasploit payload?

### ISSUE THREAD

**Issue by hktalent** [zerosum0x0/koadic#73]
how use sta/js/mshta in metasploit payload?
thanks

sta/js/mshta is by pass win10 🌸👍👍

**Comment by TheNaterz** [comment]
All Koadic stagers are just windows shell commands, so any Metasploit payloads that allows you to set a command will work. A personal favorite is auxiliary/admin/smb/psexec_command.

**Comment by hktalent** [comment]
@TheNaterz thanks
