### ISSUE TITLE
Powershell runtime integration with js/vbs.

### ISSUE THREAD

**Issue by vvalien** [zerosum0x0/koadic#8]
Just a quick note, I think its possible (it is with csharp) to be able to set the powershell runtime and inject any powershell commands we want, without the need for powershell.exe installed obviously.

If we are able to support this through a module then we can start working on integrating all the powershell scripts that empire supports. This would be ideal as there is no need to rewrite them to be compatible with koadic.

I see no reason this isn't feasible even if it has to be done with DotNetToJScript. When I get some time I'll look into it and get a script out for testing.

**Comment by gabemarshall** [comment]
I've got a working example for jscript that I'd be happy to help implement.. I'm not sure what it'd take to get it to work with vbscript though.

**Comment by TheNaterz** [comment]
![jQ25QT3iucV6Q5laOXWTQTgYS6BLwi89](https://user-images.githubusercontent.com/2198138/57152770-980a2d00-6d91-11e9-90b6-6dbd5eaeede1.gif)
