### ISSUE TITLE
API

### ISSUE THREAD

**Issue by generatorada** [zerosum0x0/koadic#80]
Good day
can anyone tell me how to make the right curl API request
I tried all the options ((
thank

**Comment by TheNaterz** [comment]
Documenting the API and putting it in the wiki one of the things that I really need to get around to doing. Make sure that you're running the rest server first by using the 'api' command. This will print out your username and password along with the API token (in case you don't want to bother "logging in").

Any requests to POST or DELETE are simply form values. Responses will contain JSON. Let me know if there's anything specific that you're trying to accomplish!

**Comment by generatorada** [comment]
The whole problem is that I can not pass authorization by login password or by token.

**Comment by TheNaterz** [comment]
Alright, let's break it down.

This is the authentication for the API: https://github.com/zerosum0x0/koadic/blob/c4b49bc69987c37303169062eb984ff528ad8828/core/rest_server.py#L89-L97

This will give you the token needed to make API requests. And this is the token validation:
https://github.com/zerosum0x0/koadic/blob/c4b49bc69987c37303169062eb984ff528ad8828/core/rest_server.py#L66-L71

If you need to get the token, you can make a POST request to /api/login. If your username is koadic and password is koadic, then the corresponding CURL command looks like this:
`curl -X POST -d "username=koadic&password=koadic" http://xx.xx.xx.xx:9990/api/login`

There's a forced 2 seconds between every attempt. If successful, then the response will look like this:
`{"token":"xxxxx..."}`

Now you can use the token for further requests. Here's the request handler for getting your running listeners:
https://github.com/zerosum0x0/koadic/blob/c4b49bc69987c37303169062eb984ff528ad8828/core/rest_server.py#L116-L127

So the corresponding CURL command looks like this:
`curl http://xx.xx.xx.xx:9990/api/listeners?token=xxxxx...`

And response:
```
{"listeners":[{"hostname":"xx.xx.xx.xx","module":"stager/js/mshta","payload_id":0,"port":"9999"}],"success":true}
```

**Comment by generatorada** [comment]
Thank you
