### ISSUE TITLE
Feature Request: Configure HTTPS in wiki

### ISSUE THREAD

**Issue by ThunderousDreamer** [zerosum0x0/koadic#83]
If possible, I'd like to see an article explaining how to set up the HTTPS certs/communication in the wiki, ideally with some quick steps to follow and then how to use it. I played around with it a bit but unfortunately not proficient enough to get it working and this article would be much appreciated.

**Comment by TheNaterz** [comment]
This is a good idea, I'll try and get something in the wiki when I can!

**Comment by zerosum0x0** [comment]
More info in 52c700fca7ff0bf361036022e364ac26fc1a41fe
