### ISSUE TITLE
Issue with hashdump_dc

### ISSUE THREAD

**Issue by kabendator** [zerosum0x0/koadic#84]
Hello there,

I'm facing error while trying to execute hashdump_dc (most of the modules work fine, checked about 90% of functionalities), and after couple of days spent "googling" with no luck decided to refer to gurus )

Shortly, the error, when runing:

(koadic: imp/gat/hashdump_dc)# run
[*] Zombie 1: Job 5 (implant/gather/hashdump_dc) created.
[*] Zombie 1: Job 5 (implant/gather/hashdump_dc) received NTDS.DIT file (35540842 bytes)
[*] Zombie 1: Job 5 (implant/gather/hashdump_dc) received SYSTEM hive (16630491 bytes)
(koadic: imp/gat/hashdump_dc)# Exception in thread Thread-998:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "modules/implant/gather/hashdump_dc.py", line 113, in finish_up
    self.ntds_file = self.save_file(self.ntds_data, 'NTDS', self.ntds_encoder)
AttributeError: 'HashDumpDCJob' object has no attribute 'ntds_encoder'

If it's some kinda looser's issue, please don't beat me hard, I'm a newbie with programming and such a serious project like Koadic.

Tnx in advance!

**Comment by TheNaterz** [comment]
Yeah, I did some janky work with hashdump_sam a while back to alleviate an issue where files that were too large were crashing hashdump. I'll try investigating a little this week and see if I can get a fix out!
