### ISSUE TITLE
Bug in isElevated() when Server service disabled

### ISSUE THREAD

**Issue by zerosum0x0** [zerosum0x0/koadic#87]
We use `net session` output to determine if we are high integrity.

When Server service is disabled, you get this output:

```
C:\>net session
The Server service is not started.

More help is available by typing NET HELPMSG 2114.

C:\>NET HELPMSG 2114

The Server service is not started.

(lol)
```

Our zombie now falsely reports that we are high integrity.

There really aren't a whole lot of good ways for us to check this, it's an odd quirk and probably fine but just making a note of it in case someone runs into it or offers a suggestion.

**Comment by TheNaterz** [comment]
Did some testing, think I have a solution.

```
Koadic.user.isElevated = function()
{
    try
    {
        var res = Koadic.shell.exec("(net session || echo unelevated)", "%TEMP%\\"+Koadic.uuid()+".txt");
        if (res.indexOf("unelevated") == -1)
        {
            return true;
        }
        if (res.indexOf("2114") == -1)
        {
            return false;
        }
        else
        {
            var res2 = Koadic.shell.exec("net continue lanmanserver", "%TEMP%\\"+Koadic.uuid()+".txt");
            if (res2.indexOf("5") == -1)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
    catch(e)
    {
        return false;
    }
}
```

Will need to test on some other versions of Windows before pushing.

**Comment by TheNaterz** [comment]
We could also try running NET PAUSE LanmanServer. If you're unelevated, you get a System error 5 regardless of running status. If elevated, this command doesn't do anything since if it's running, it's not a valid command for the service. If it's not running, it just says it's not running.
