### ISSUE TITLE
bypassuac(both modules) leave fragments if uac setting is highest.

### ISSUE THREAD

**Issue by vvalien** [zerosum0x0/koadic#9]
I would like someone else to confirm this if possible, on Win10 if the UAC setting is set to the highest and the user clicks no when the elevate box pops, the registry fragments are left behind.

While this has its own SE implications, (and bypass implications) it can be really bad (for us) as whenever a .exe (depending on module) is set to run under high integrity it will prompt a box asking if cmd.exe can be run with the payload chosen.

Two fixes come to mind the first... rewriting it to ensure deletion on fail. The second I think is a much better option. We can first check the registry key here `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\ConsentPromptBehaviorAdmin` 
to determine what setting it is on, and then error out if it is to high. Just for completeness I checked and these are the levels.

highest = 2
normal = 5

**Comment by zerosum0x0** [comment]
Good catch. We can check that registry key pretty easily. Do we only need to check != 2? Weird numbering in that enum.

**Comment by vvalien** [comment]
Yep that should work, I was kicking around the idea of making it a method that the implant calls after load and posting it back like the IP, Hostname, etc...  but I cant see any reason it would be needed, unless its to let the operator know that the user is above average and needs to be cautious...

I'm digging around in the implant code now and should hopefully have this committed tomorrow.

**Comment by dxflatline** [comment]
Exact the same here!
It is also very interesting that procmon.exe itself, is looking for IsolatedCommand in registry, so I had this leftovers behind and could run procmon! Took some time to troubleshoot.
I would definetely add a registry.destroy in the catch block (also for eventvwr method) just in case
