### ISSUE TITLE
Termux installation 

### ISSUE THREAD

**Issue by Darkcast** [zerosum0x0/koadic#95]
Tried to install it on termux and I almost got away with if it wasn't for those darn kids and their dog. I mean one of the dependencies failed. 
Let me know if there something I can do fix it. 
[output.txt](https://github.com/zerosum0x0/koadic/files/3070466/output.txt)

**Comment by TheNaterz** [comment]
Was able to replicate on my device. The error "unable to execute 'aarch64-linux-android-clang': No such file or directory" stands out, so a little google-fu led me [here](https://github.com/neovim/pynvim/issues/267) and [here](https://github.com/geerlingguy/JJG-Ansible-Windows/issues/28). Sorted out a few more dependency errors, and then got it to work.

`apt install clang python-dev libffi-dev openssl-dev`

Let me know if that works for ya.

**Comment by Darkcast** [comment]
I previously tried instaling clang and libfffi but it didnt work, I will try with openssl-dev and pydev I will report back as soon as I can. Thanks for your help

**Comment by Darkcast** [comment]
Workerd flawlessly, thanks. 
hope this gets added to the READ.ME
