### ISSUE TITLE
Error with "implant/inject/mimikatz_dotnet2js"

### ISSUE THREAD

**Issue by katesaikishore** [zerosum0x0/koadic#98]
I have done all the steps shown in the video!
And it is a freshly installed windows machine with no AV.

![Screenshot 2019-04-25 at 8 02 04 PM](https://user-images.githubusercontent.com/10182914/56743909-19abfa80-6795-11e9-809d-3c26b3f131af.png)

**Comment by TheNaterz** [comment]
You need to be elevated in order to run mimikatz. Either run the stager from an elevated command prompt or use one of the privilege escalation modules under implant/elevate/*.

**Comment by katesaikishore** [comment]
OK Let me try this! Btw how can we use this in public domain! As it shows the home network?

**Comment by TheNaterz** [comment]
Koadic has domain awareness capabilities when run with implant/gather/enum_domain_info. If you run Koadic on domain-joined machines, it will display the primary domain controller under zombie info.

**Comment by katesaikishore** [comment]
And the major problem has been resolved elevated the credits!
And Please add the camera access feature.
Thank You very much for your support!
